

aruco_markers:


  0:
    x:      0.0
    y:      3.90      # 4.86 - 1.01 + 0.05
    z:      0.18
    roll:   1.5708
    pitch:  0.0
    yaw:    1.5708    # π/2 → Z 

  4:
    x:      0.0
    y:      1.04      # 0.99 + 0.05
    z:      0.18
    roll:   1.5708
    pitch:  0.0
    yaw:    1.5708    # π/2 → Z 

  2:
    x:      3.76
    y:      3.90
    z:      0.18
    roll:   1.5708
    pitch:  0.0
    yaw:   -1.5708    # -π/2 → Z 


  3:
    x:      3.76
    y:      1.04
    z:      0.18
    roll:   1.5708
    pitch:  0.0
    yaw:   -1.5708    # -π/2 → Z 
